version: 2
updates:
- package-ecosystem: nuget
  directory: "/Kanban"
  schedule:
    interval: daily
    time: "07:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
